### ISSUE TITLE
alt-enter and alt-backspace doesn't seem to work to accept/cancel edits (though clicking the buttons works)

### ISSUE THREAD

**Issue by treefrog00** [codestoryai/aide#936]
### Before submitting your bug report

- [ ] I'm not able to find an [open issue](https://github.com/codestoryai/sidecar/issues) that reports the same bug

### Environment

```Markdown
- OS: x64 Ubuntu
- Sidecar commit:
- IDE commit:
```

### Description

on my machine alt-enter and alt-backspace doesn't seem to work to accept/cancel edits (though clicking the buttons works)

**Comment by theskcd** [comment]
This is gonna get resolved with the latest build (which is shipping today)

**Comment by theskcd** [comment]
https://github.com/codestoryai/aide/commit/c6b6de6739388d21346f0832e6dd104b1f29fac5 this is resolved now! let us know if this does not work
