### ISSUE TITLE
Pinned context doesn't save without hitting 'OK'. Saving on blur would be handy.

### ISSUE THREAD

**Issue by treefrog00** [codestoryai/aide#937]
### Before submitting your bug report

- [ ] I'm not able to find an [open issue](https://github.com/codestoryai/sidecar/issues) that reports the same bug

### Environment

```Markdown
- OS: x64 Ubuntu
- Sidecar commit:
- IDE commit:
```

**Comment by ghostwriternr** [comment]
Hey @jamesjrg! Apologies for missing this one earlier. Can you describe the issue a bit more? I'm not quite sure if I follow the issue being described here. Even just a screenshot would be quite helpful!

**Comment by treefrog00** [comment]
It's not a problem if you are using the keyboard to navigate the UI, so it's a tiny thing, but for people using the mouse, I think the lack of auto-save will be confusing:

**Comment by treefrog00** [comment]
[Screencast from 11-11-24 11:51:18.webm](https://github.com/user-attachments/assets/65669297-900b-4579-8ef8-9c0edbc590b4)

**Comment by ghostwriternr** [comment]
Aha, got it! That makes a lot of sense. Thank you. Will ensure this is addressed.

**Comment by ghostwriternr** [comment]
Fixed in https://github.com/codestoryai/aide/pull/964. Will land on the next release.
