### ISSUE TITLE
Keyboard shortcuts to accept/reject edits don't work

### ISSUE THREAD

**Issue by ghostwriternr** [codestoryai/aide#943]
### Before submitting your bug report

- [X] I'm not able to find an [open issue](https://github.com/codestoryai/sidecar/issues) that reports the same bug

### Environment

```Markdown
- OS: Linux
```

### Reproduction

Clicking the buttons to accept/reject changes works after the assistant makes an edit, but not when pressing the suggested key combination

**Comment by theskcd** [comment]
https://github.com/codestoryai/aide/commit/c6b6de6739388d21346f0832e6dd104b1f29fac5 this is now resolved!
