### ISSUE TITLE
AI Assistant Edits Accepted Revert After Coming Back To Page 

### ISSUE THREAD

**Issue by ericchambers-chattie** [codestoryai/aide#949]
### Before submitting your bug report

- [X] I'm not able to find an [open issue](https://github.com/codestoryai/sidecar/issues) that reports the same bug

### Environment

```Markdown
- OS: macOS Montery 12.6.4, Apple M1 Pro
- Sidecar commit: n/a
- IDE commit: n/a
```

### Description

When asking the AI to edit the code, it will write a plan, I accept the plan, it saves the changes, then when I leave to another page and come back its as if the edit was not accepted. Please see screenshots below:

<img width="3120" alt="1" src="https://github.com/user-attachments/assets/a2f11743-f83a-477d-94e7-17b4f5781635">
<img width="3120" alt="2" src="https://github.com/user-attachments/assets/b86cbf1c-2b88-45ab-8861-a97d76198ecc">
<img width="3120" alt="3" src="https://github.com/user-attachments/assets/af645a14-4d64-43a6-a9a3-164ba842d56f">
<img width="3120" alt="4" src="https://github.com/user-attachments/assets/25928012-c7d6-4831-bdde-5dfe2215046a">

### Reproduction

1. Accept AI edits.
2. Navigate to another page.
3. Come back to page that was edited by the AI.

**Comment by theskcd** [comment]
Thank you for reporting.. taking a look
